version: "3.5"
# TODO: Modify every service so it uses proper images, proper networking etc.
services:
  postgresql:
    image: postgres
    volumes:
      - postgres-data:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: python-forum-assignment
    networks:
      - assigment_network

  rabbitmq:
    image: rabbitmq
    networks:
      - assigment_network

  app:
    # Does not use preexisting image, it should be built using Dockerfile.app
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - assigment_network

  init:
    # Optional, initialization can also be done through app build
    build:
      context: .
      dockerfile: Dockerfile.init
    networks:
      - assigment_network

  # Optional, for every new service, a docker-compose service should be added
  redis:
    image: redis
    restart: always
    networks:
      - assigment_network

networks:
  assigment_network:
    external: false
    name: assigment_network

volumes:
  postgres-data:

