"""Unique constraint on user_id in Thread deleted.

Revision ID: 0628783f9609
Revises: e8bd968be556
Create Date: 2022-09-18 13:12:08.017560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0628783f9609'
down_revision = 'e8bd968be556'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('threads_user_id_key', 'threads', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('threads_user_id_key', 'threads', ['user_id'])
    # ### end Alembic commands ###
