"""change user_has_message

Revision ID: e8bd968be556
Revises: 3372016065bc
Create Date: 2022-09-17 12:21:20.417051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bd968be556'
down_revision = '3372016065bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'association', ['message_id'])
    op.create_unique_constraint(None, 'association', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association', type_='unique')
    op.drop_constraint(None, 'association', type_='unique')
    # ### end Alembic commands ###
