"""Create post,message and comment.

Revision ID: d052d9d6aa4e
Revises: 156c8f27c644
Create Date: 2022-09-14 20:49:39.761541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd052d9d6aa4e'
down_revision = '156c8f27c644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dtCreated', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('recipient_id'),
    sa.UniqueConstraint('sender_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('dtCreated', sa.DateTime(), nullable=True),
    sa.Column('dtUpdated', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'thread_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('thread_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('dtCreated', sa.DateTime(), nullable=True),
    sa.Column('dtUpdated', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('post_id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('user_thread_link')
    op.alter_column('threads', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('threads', 'dtCreated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('threads', 'dtUpdated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('threads', 'dtUpdated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('threads', 'dtCreated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('threads', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('user_thread_link',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='user_thread_link_thread_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='user_thread_link_users_id_fkey'),
    sa.PrimaryKeyConstraint('users_id', 'thread_id', name='user_thread_link_pkey'),
    sa.UniqueConstraint('thread_id', name='user_thread_link_thread_id_key'),
    sa.UniqueConstraint('users_id', name='user_thread_link_users_id_key')
    )
    op.drop_table('comments')
    op.drop_table('attachments')
    op.drop_table('posts')
    op.drop_table('messages')
    # ### end Alembic commands ###
