"""user_has_message added.

Revision ID: 3372016065bc
Revises: f9235a7f8424
Create Date: 2022-09-17 11:48:56.834176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3372016065bc'
down_revision = 'f9235a7f8424'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
