"""Delete name from user

Revision ID: 134c4dc67760
Revises: 3632eb6b8027
Create Date: 2022-09-19 21:29:37.429572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134c4dc67760'
down_revision = '3632eb6b8027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
