"""Third migration

Revision ID: 4c529c472c9e
Revises: 33e119e27a5e
Create Date: 2022-09-12 23:38:08.054148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c529c472c9e'
down_revision = '33e119e27a5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(None, 'threads', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])

    # op.create_table('user_thread_link',
    # sa.Column('users_id', sa.Integer(), nullable=False),
    # sa.Column('thread_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    # sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('users_id', 'thread_id'),
    # sa.UniqueConstraint('thread_id'),
    # sa.UniqueConstraint('users_id'),
    #
    # )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    # op.drop_constraint(None, 'threads', type_='unique')
    op.drop_table('user_thread_link')
    # ### end Alembic commands ###
