"""empty message

Revision ID: 97bf6fd90379
Revises: 55cfba60c419
Create Date: 2022-09-15 22:46:27.801001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97bf6fd90379'
down_revision = '55cfba60c419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('messages')
    op.drop_table('attachments')
    op.drop_table('posts')
    op.drop_table('threads')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('posts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dtCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dtUpdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='posts_thread_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'thread_id', name='posts_pkey'),
    sa.UniqueConstraint('id', name='posts_id_key'),
    sa.UniqueConstraint('thread_id', name='posts_thread_id_key'),
    sa.UniqueConstraint('user_id', name='posts_user_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='attachments_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey'),
    sa.UniqueConstraint('post_id', name='attachments_post_id_key')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('id', name='users_id_key'),
    sa.UniqueConstraint('id', name='users_id_key1'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('threads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('threads_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dtCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dtUpdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='threads_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='threads_pkey'),
    sa.UniqueConstraint('id', name='threads_id_key'),
    sa.UniqueConstraint('id', name='threads_id_key1'),
    sa.UniqueConstraint('user_id', name='threads_user_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dtCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='messages_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='messages_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey'),
    sa.UniqueConstraint('id', name='messages_id_key'),
    sa.UniqueConstraint('recipient_id', name='messages_recipient_id_key'),
    sa.UniqueConstraint('sender_id', name='messages_sender_id_key')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dtCreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dtUpdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='comments_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    sa.UniqueConstraint('id', name='comments_id_key'),
    sa.UniqueConstraint('post_id', name='comments_post_id_key'),
    sa.UniqueConstraint('user_id', name='comments_user_id_key')
    )
    # ### end Alembic commands ###
