"""Uique constraint removed for foregin keys in Comment table

Revision ID: 3632eb6b8027
Revises: 422038e78180
Create Date: 2022-09-19 01:18:29.923811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3632eb6b8027'
down_revision = '422038e78180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_key', 'comments', type_='unique')
    op.drop_constraint('comments_user_id_key', 'comments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comments_user_id_key', 'comments', ['user_id'])
    op.create_unique_constraint('comments_post_id_key', 'comments', ['post_id'])
    # ### end Alembic commands ###
