"""Fourth migration

Revision ID: 156c8f27c644
Revises: 4c529c472c9e
Create Date: 2022-09-13 19:06:18.910637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156c8f27c644'
down_revision = '4c529c472c9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_thread_link',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'thread_id'),
    sa.UniqueConstraint('thread_id'),
    sa.UniqueConstraint('users_id')
    )
    op.add_column('threads', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'threads', ['user_id'])
    op.create_foreign_key(None, 'threads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_constraint(None, 'threads', type_='unique')
    op.drop_column('threads', 'user_id')
    op.drop_table('user_thread_link')
    # ### end Alembic commands ###
